### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ShardulNalegave** [DeltaCoderr/live-weather#2]
DarkSky has recently been acquired by Apple. They are now not an open project. It seems you are using the API service provided by. The two problems with it now are:-
- No one can contribute to your repo! DarkSky has stopped accepting new sign ups.
- Your app will stop working from 2021 (not much time left). DarkSky has announced that their registered users can continue to access the service till 2021 for migration purposes and from 2021 APIs will not work. 

For more information visit: [DarkSky Announcement on their Blog](https://blog.darksky.net/)

**Comment by sbdh11** [comment]
Ah, I got it I didn't visit the DarkSky Website at the first place but realized  it now, Thanks for opening this Issue!
Well actually I was just surfing through the net about the weather API'S and many websites had "DarkSky"  in their recommendation so I thought I could rely on it. I  visited their blog it seems they have been acquired by Apple.

**Comment by sbdh11** [comment]
I agree the API won't work in 2020, But I didn't find any other API's that were much useful and provide all the information regarding this. I will keep this issue open just in case if you want to talk more about it or suggest more of these API's

**Comment by ShardulNalegave** [comment]
You might want to try using the [Open Weather Map API](https://openweathermap.org/). It has a free version which allows up to 60 calls per minute, which is reasonable for a project.

**Comment by ShardulNalegave** [comment]
Also hosting on [Glitch](https://glitch.me) might be a bad idea as the code will be exposed through multiple sources. Try using [Netlify](https://netlify.com). It is available for free and have nice domain names. I have used it for many of my projects without any problem.

**Comment by sbdh11** [comment]
> Also hosting on [Glitch](https://glitch.me) might be a bad idea as the code will be exposed through multiple sources. Try using [Netlify](https://netlify.com). It is available for free and have nice domain names. I have used it for many of my projects without any problem.

Well, Glitch has an option to hide your source code  so that it won't be exposed through multiple sources and I am pretty familiar with How Glitch works, I might give a try to Netlify, But  Later on.

**Comment by sbdh11** [comment]
> You might want to try using the [Open Weather Map API](https://openweathermap.org/). It has a free version which allows up to 60 calls per minute, which is reasonable for a project.

Will Check it
